title: junseokim19
description: # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: ''
url: "https://junseokim19.github.io"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Junseo Kim # add your name
author-img: My/photo.jpg # add your photo
about-author: Research & Project
#social-twitter:  # add your Twitter handle
social-facebook: kim.junseo.12 # add your Facebook handle
social-github: junseokim19 # add your Github handle
social-linkedin: junseo-kim-875b5424b # add your Linkedin handle
social-email: kimjs990919@gmail.com # add your Email address

# Disqus
discus-identifier: junseokim19 # add your discus identifier

# Tracker
analytics: Google Analytics

# Build Settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
